# Generated by Django 3.0.8 on 2020-07-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuserr',
            name='pin',
            field=models.CharField(default='21I67', max_length=5),
        ),
    ]
