# Generated by Django 3.0.8 on 2020-07-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0002_adminuserr_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuserr',
            name='pin',
            field=models.CharField(default='S7GML', max_length=5),
        ),
    ]
