# Generated by Django 3.0.8 on 2020-07-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0003_auto_20200728_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super_Registeradmin',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='adminuserr',
            name='pin',
            field=models.CharField(default='ZUOE9', editable=False, max_length=5),
        ),
        migrations.CreateModel(
            name='AdminUserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digivotapp.AdminUserR')),
            ],
        ),
    ]
