# Generated by Django 3.0.8 on 2020-07-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0005_auto_20200728_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuserr',
            name='pin',
            field=models.CharField(default='A8PHZ', editable=False, max_length=5),
        ),
        migrations.DeleteModel(
            name='AdminUserLogin',
        ),
    ]
