# Generated by Django 3.0.8 on 2020-07-31 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0006_auto_20200729_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Super_Registeradmin',
        ),
        migrations.RemoveField(
            model_name='adminuserr',
            name='pin',
        ),
    ]
