# Generated by Django 3.0.8 on 2020-08-01 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0007_auto_20200731_2330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUserR',
        ),
    ]
