# Generated by Django 3.0.8 on 2020-08-01 00:28

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digivotapp', '0008_delete_adminuserr'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserR',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('othername', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+234**********'. 14 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=100)),
                ('DOB', models.DateField()),
                ('address', models.TextField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Female', max_length=50)),
                ('status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], default='status', max_length=50)),
                ('states', models.CharField(choices=[('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara'), ('fct', 'FCT')], max_length=50)),
                ('region', models.CharField(default='surulere', max_length=50)),
                ('pictures', models.ImageField(upload_to='Images/')),
                ('finger1', models.BinaryField()),
                ('finger2', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectionType',
            fields=[
                ('electionID', models.AutoField(primary_key=True, serialize=False)),
                ('electiontype', models.CharField(max_length=100)),
                ('registeration_start', models.DateField()),
                ('registeration_end', models.DateField()),
                ('voting_start', models.DateField()),
                ('voting_end', models.DateField()),
                ('requiredposition', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('lgaID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerUserR',
            fields=[
                ('managerID', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('othername', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+234**********'. 14 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=100)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Female', max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('pictures', models.ImageField(upload_to='Images/')),
                ('finger1', models.BinaryField()),
                ('finger2', models.BinaryField()),
                ('pin', models.CharField(default='MW4IG', editable=False, max_length=5)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digivotapp.AdminUserR')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('partyID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('acronym', models.CharField(max_length=10)),
                ('symbol', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('stateID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Super_Registeradmin',
            fields=[
                ('pin', models.CharField(default='AXTBE', editable=False, max_length=5, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('wardID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lgaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digivotapp.LGA')),
            ],
        ),
        migrations.CreateModel(
            name='VoterReg',
            fields=[
                ('voterID', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('othername', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+234**********'. 14 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=100)),
                ('DOB', models.DateField()),
                ('status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], default='status', max_length=50)),
                ('title', models.CharField(choices=[('mr', 'Mr'), ('ms', 'Ms'), ('mrs', 'Mrs')], max_length=50)),
                ('statesoforigin', models.CharField(choices=[('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara'), ('fct', 'FCT')], max_length=50)),
                ('regionoforigin', models.CharField(default='surulere', max_length=50)),
                ('statesofresidence', models.CharField(choices=[('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara'), ('fct', 'FCT')], max_length=50)),
                ('regionofresidence', models.CharField(default='surulere', max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('pictures', models.ImageField(upload_to='Images/')),
                ('finger1', models.BinaryField()),
                ('finger2', models.BinaryField()),
                ('pin', models.CharField(default='GYXC0', editable=False, max_length=5)),
                ('managerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digivotapp.ManagerUserR')),
            ],
        ),
        migrations.CreateModel(
            name='SenatorialDistrict',
            fields=[
                ('districtID', models.AutoField(primary_key=True, serialize=False)),
                ('districtname', models.CharField(max_length=50)),
                ('composition', models.TextField(max_length=100)),
                ('stateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digivotapp.State')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalPost',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('electionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digivotapp.ElectionType')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalCandidate',
            fields=[
                ('candidateID', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_firstname', models.CharField(max_length=50)),
                ('candidate_othername', models.CharField(max_length=50)),
                ('candidate_surname', models.CharField(max_length=50)),
                ('candidate_details', models.TextField(max_length=200)),
                ('running_firstname', models.CharField(max_length=50)),
                ('running_othername', models.CharField(max_length=50)),
                ('runningmate_surname', models.CharField(max_length=50)),
                ('runningmate_details', models.TextField(max_length=200)),
                ('electionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digivotapp.ElectionType')),
                ('partyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digivotapp.PoliticalParty')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerUserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('managerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digivotapp.ManagerUserR')),
            ],
        ),
        migrations.AddField(
            model_name='lga',
            name='stateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digivotapp.State'),
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('voteID', models.AutoField(primary_key=True, serialize=False)),
                ('dateadded', models.DateTimeField(default=datetime.date(2020, 8, 1))),
                ('timeadded', models.DateTimeField(default=datetime.datetime(2020, 8, 1, 0, 28, 40, 826392, tzinfo=utc))),
                ('candidateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digivotapp.PoliticalCandidate')),
                ('voters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digivotapp.VoterReg')),
            ],
        ),
        migrations.CreateModel(
            name='AdminUserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digivotapp.AdminUserR')),
            ],
        ),
    ]
