# Generated by Django 3.0.8 on 2020-08-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0009_auto_20200801_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='timeadded',
        ),
        migrations.AlterField(
            model_name='ballot',
            name='dateadded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manageruserr',
            name='pin',
            field=models.CharField(default='M3P2P', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='super_registeradmin',
            name='pin',
            field=models.CharField(default='A6K0G', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voterreg',
            name='pin',
            field=models.CharField(default='GJK8Y', editable=False, max_length=5),
        ),
    ]
