# Generated by Django 3.0.8 on 2020-08-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0014_auto_20200801_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageruserr',
            name='pin',
            field=models.CharField(default='MRMIE', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='super_registeradmin',
            name='pin',
            field=models.CharField(default='APFFN', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voterreg',
            name='pin',
            field=models.CharField(default='VHOHZ', editable=False, max_length=5),
        ),
    ]
