# Generated by Django 3.0.8 on 2020-08-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0015_auto_20200801_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageruserr',
            name='adminID',
        ),
        migrations.AlterField(
            model_name='manageruserr',
            name='pin',
            field=models.CharField(default='MQ45R', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='super_registeradmin',
            name='pin',
            field=models.CharField(default='ANYAT', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voterreg',
            name='pin',
            field=models.CharField(default='VF1HQ', editable=False, max_length=5),
        ),
    ]
