# Generated by Django 3.0.8 on 2020-08-02 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0016_auto_20200802_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageruserr',
            name='dateadded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='manageruserr',
            name='pin',
            field=models.CharField(default='MS2YH', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='super_registeradmin',
            name='pin',
            field=models.CharField(default='A4ATT', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voterreg',
            name='pin',
            field=models.CharField(default='VMOKR', editable=False, max_length=5),
        ),
    ]
