# Generated by Django 3.0.8 on 2020-08-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0018_auto_20200802_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageruserr',
            name='pin',
            field=models.CharField(default='MU05G', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='super_registeradmin',
            name='pin',
            field=models.CharField(default='AFCLW', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voterreg',
            name='pin',
            field=models.CharField(default='V1KDC', editable=False, max_length=5),
        ),
    ]
