# Generated by Django 3.0.8 on 2020-08-02 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0019_auto_20200802_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageruserr',
            name='finger1',
        ),
        migrations.RemoveField(
            model_name='manageruserr',
            name='finger2',
        ),
        migrations.AddField(
            model_name='electiontype',
            name='dateadded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='politicalcandidate',
            name='dateadded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='manageruserr',
            name='pin',
            field=models.CharField(default='MY1BL', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='super_registeradmin',
            name='pin',
            field=models.CharField(default='AP73F', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voterreg',
            name='pin',
            field=models.CharField(default='VDXA1', editable=False, max_length=5),
        ),
    ]
