# Generated by Django 3.0.8 on 2020-08-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0020_auto_20200802_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politicalparty',
            old_name='name',
            new_name='partyname',
        ),
        migrations.RenameField(
            model_name='politicalparty',
            old_name='symbol',
            new_name='partysymbol',
        ),
        migrations.RemoveField(
            model_name='politicalparty',
            name='acronym',
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='partyacronym',
            field=models.CharField(default='ttt', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manageruserr',
            name='pin',
            field=models.CharField(default='MTDQC', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='super_registeradmin',
            name='pin',
            field=models.CharField(default='ASBOX', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voterreg',
            name='pin',
            field=models.CharField(default='VBHYQ', editable=False, max_length=5),
        ),
    ]
