# Generated by Django 3.0.8 on 2020-08-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0021_auto_20200803_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='electiontype',
            name='electiontitle',
            field=models.CharField(default='Thefirstelection', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manageruserr',
            name='pin',
            field=models.CharField(default='MM0TP', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='super_registeradmin',
            name='pin',
            field=models.CharField(default='ADR15', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voterreg',
            name='pin',
            field=models.CharField(default='VF3KB', editable=False, max_length=5),
        ),
    ]
