# Generated by Django 3.0.8 on 2020-08-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0022_auto_20200803_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='electiontype',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Female', max_length=50),
        ),
        migrations.AlterField(
            model_name='electiontype',
            name='electiontype',
            field=models.CharField(choices=[('presidential', 'Presidential'), ('gubernatorial', 'Gubernatorial'), ('senatorial', 'Senatoial')], default='Presidential', max_length=100),
        ),
        migrations.AlterField(
            model_name='manageruserr',
            name='pin',
            field=models.CharField(default='MSSUB', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='super_registeradmin',
            name='pin',
            field=models.CharField(default='ALYER', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voterreg',
            name='pin',
            field=models.CharField(default='VMVG2', editable=False, max_length=5),
        ),
    ]
