# Generated by Django 3.0.8 on 2020-08-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0023_auto_20200804_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiontype',
            name='registeration_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='electiontype',
            name='registeration_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='manageruserr',
            name='pin',
            field=models.CharField(default='MBXB7', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='super_registeradmin',
            name='pin',
            field=models.CharField(default='ADFKZ', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voterreg',
            name='pin',
            field=models.CharField(default='VPCM5', editable=False, max_length=5),
        ),
    ]
