# Generated by Django 3.0.8 on 2020-08-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0024_auto_20200804_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electiontype',
            name='gender',
        ),
        migrations.AlterField(
            model_name='manageruserr',
            name='pin',
            field=models.CharField(default='MGM90', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='super_registeradmin',
            name='pin',
            field=models.CharField(default='AWI2P', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voterreg',
            name='pin',
            field=models.CharField(default='VV2BY', editable=False, max_length=5),
        ),
    ]
