# Generated by Django 3.0.8 on 2020-08-05 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0025_auto_20200805_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiontype',
            name='dateadded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='electiontype',
            name='registeration_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='electiontype',
            name='registeration_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='manageruserr',
            name='pin',
            field=models.CharField(default='MCJNE', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='super_registeradmin',
            name='pin',
            field=models.CharField(default='AMA45', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voterreg',
            name='pin',
            field=models.CharField(default='V9EJU', editable=False, max_length=5),
        ),
    ]
