# Generated by Django 3.0.8 on 2020-08-06 08:33

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('digivotapp', '0027_auto_20200805_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageruserr',
            name='pictures',
            field=stdimage.models.StdImageField(upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='manageruserr',
            name='pin',
            field=models.CharField(default='MXYP3', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='super_registeradmin',
            name='pin',
            field=models.CharField(default='AZILW', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voterreg',
            name='pin',
            field=models.CharField(default='V4QRT', editable=False, max_length=5),
        ),
    ]
